# Generated by Django 2.0.6 on 2019-04-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('born_date', models.DateField(blank=True, verbose_name='出生日期')),
                ('gender', models.CharField(blank=True, choices=[('boy', '男孩'), ('girl', '女孩')], max_length=12, verbose_name='性别')),
                ('grade', models.CharField(blank=True, choices=[('BS', '未上学'), ('KSSC', '幼儿园小小班'), ('KSC', '幼儿园小班'), ('KMC', '幼儿园中班'), ('KC', '幼儿园大班'), ('GO', '一年级'), ('GT', '二年级'), ('GTH', '三年级'), ('GF', '四年级'), ('GFI', '五年级'), ('GS', '六年级'), ('GSE', '初一'), ('GE', '初二'), ('GN', '初三'), ('HO', '高一'), ('HT', '高二'), ('HTW', '高三')], max_length=12, verbose_name='年级')),
                ('another_contact_name', models.CharField(blank=True, max_length=32, verbose_name='备用联系人')),
                ('another_contact_phonenumber', models.CharField(blank=True, max_length=11, verbose_name='备用联系电话')),
                ('is_allergy', models.BooleanField(default=False, verbose_name='是否有过敏史')),
                ('allergy', models.TextField(blank=True, verbose_name='过敏史')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='图片')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Shangjia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='商户名称')),
                ('location', models.CharField(default='{}', max_length=256, verbose_name='地理位置')),
                ('is_real_time_monitoring', models.BooleanField(default=False, verbose_name='实时监控')),
                ('is_purchase_insurance', models.BooleanField(default=False, verbose_name='购买保险')),
                ('is_Verified', models.BooleanField(default=False, verbose_name='实名认证')),
                ('is_academic_certificate', models.BooleanField(default=False, verbose_name='学历认证')),
                ('is_Health_certification', models.BooleanField(default=False, verbose_name='健康认证')),
                ('introduction', models.CharField(max_length=256, verbose_name='商家介绍')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openID', models.CharField(max_length=32, unique=True)),
                ('nickname', models.CharField(max_length=256)),
            ],
        ),
    ]
