# Generated by Django 2.0.6 on 2019-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190417_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shangjia',
            name='latitude',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='用户所在纬度'),
        ),
        migrations.AlterField(
            model_name='shangjia',
            name='longitude',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='用户所在经度'),
        ),
    ]
