# Generated by Django 2.0.6 on 2019-04-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190419_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shangjia',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='用户所在纬度'),
        ),
        migrations.AlterField(
            model_name='shangjia',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='用户所在经度'),
        ),
    ]
