# Generated by Django 2.0.6 on 2019-04-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190419_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangjia',
            name='city',
            field=models.CharField(max_length=256, null=True, verbose_name='所在城市'),
        ),
        migrations.AddField(
            model_name='shangjia',
            name='province',
            field=models.CharField(max_length=256, null=True, verbose_name='所在省份'),
        ),
    ]
