# Generated by Django 2.2 on 2019-04-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190420_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangjia',
            name='score',
            field=models.FloatField(default=5.0, verbose_name='商家评分'),
        ),
    ]
