# Generated by Django 2.0.6 on 2019-04-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_shangjia_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='contact_name',
            field=models.CharField(max_length=32, null=True, verbose_name='紧急联系人'),
        ),
        migrations.AddField(
            model_name='child',
            name='contact_phone',
            field=models.CharField(max_length=11, null=True, verbose_name='紧急联系电话'),
        ),
    ]
