# Generated by Django 2.0.6 on 2019-05-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190424_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='born_date',
            field=models.CharField(blank=True, max_length=256, verbose_name='出生日期'),
        ),
    ]
