# Generated by Django 2.0.6 on 2019-05-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190519_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='another_contact_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='备用联系人'),
        ),
        migrations.AlterField(
            model_name='child',
            name='another_contact_phonenumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='备用联系电话'),
        ),
        migrations.AlterField(
            model_name='child',
            name='born_date',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, choices=[('boy', '男孩'), ('girl', '女孩')], max_length=12, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='child',
            name='grade',
            field=models.CharField(blank=True, choices=[('BS', '未上学'), ('KSSC', '幼儿园小小班'), ('KSC', '幼儿园小班'), ('KMC', '幼儿园中班'), ('KC', '幼儿园大班'), ('GO', '一年级'), ('GT', '二年级'), ('GTH', '三年级'), ('GF', '四年级'), ('GFI', '五年级'), ('GS', '六年级'), ('GSE', '初一'), ('GE', '初二'), ('GN', '初三'), ('HO', '高一'), ('HT', '高二'), ('HTW', '高三')], max_length=12, null=True, verbose_name='年级'),
        ),
    ]
