# Generated by Django 2.0.6 on 2019-05-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190519_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='card_type',
            field=models.CharField(default='身份证', max_length=25, verbose_name='证件类型'),
        ),
        migrations.AddField(
            model_name='child',
            name='idcard',
            field=models.CharField(default='暂无证件号码', max_length=50, verbose_name='证件号码'),
        ),
    ]
