# Generated by Django 2.0.6 on 2019-05-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190519_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='idcard',
            field=models.CharField(default='暂无证件号码', max_length=50, null=True, verbose_name='证件号码'),
        ),
    ]
