# Generated by Django 2.0.6 on 2019-04-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190416_2230'),
        ('authorization', '0002_auto_20190416_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yonghu',
            new_name='User',
        ),
    ]
