# Generated by Django 2.0.6 on 2019-04-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20190416_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='yonghu',
            name='latitude',
            field=models.PositiveIntegerField(null=True, verbose_name='用户所在纬度'),
        ),
        migrations.AddField(
            model_name='yonghu',
            name='longitude',
            field=models.PositiveIntegerField(null=True, verbose_name='用户所在经度'),
        ),
    ]
