# Generated by Django 2.0.6 on 2019-04-17 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20190417_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yonghu',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='yonghu',
            name='longitude',
        ),
    ]
