# Generated by Django 2.0.6 on 2019-05-26 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20190417_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renzheng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='姓名')),
                ('nationality', models.CharField(max_length=8, verbose_name='民族')),
                ('id_num', models.CharField(max_length=18, verbose_name='身份证号')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('birth', models.CharField(max_length=8, verbose_name='出生日期')),
                ('address', models.CharField(max_length=256, verbose_name='家庭地址')),
                ('start_date', models.CharField(max_length=8, verbose_name='有效期起始时间')),
                ('end_date', models.CharField(max_length=8, verbose_name='有效期结束时间')),
                ('issue', models.CharField(max_length=32, verbose_name='签发机关')),
                ('status', models.CharField(default='审核中', max_length=8, verbose_name='审核状态')),
                ('yonghu', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.Yonghu')),
            ],
        ),
    ]
