# Generated by Django 2.0.6 on 2019-05-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_auto_20190526_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renzheng',
            name='yonghu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='renzheng', to='authorization.Yonghu'),
        ),
    ]
