# Generated by Django 2.0.6 on 2019-05-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_auto_20190526_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renzheng',
            name='yonghu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.Yonghu'),
        ),
    ]
