# Generated by Django 2.0.6 on 2019-06-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_auto_20190526_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='renzheng',
            name='compuny',
            field=models.CharField(default='', max_length=125, verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='renzheng',
            name='cp_address',
            field=models.CharField(default='', max_length=125, verbose_name='公司地址'),
        ),
        migrations.AddField(
            model_name='renzheng',
            name='cp_data',
            field=models.CharField(default='', max_length=60, verbose_name='营业期限'),
        ),
        migrations.AddField(
            model_name='renzheng',
            name='fading_daibiao',
            field=models.CharField(default='', max_length=25, verbose_name='法定代表人'),
        ),
        migrations.AddField(
            model_name='renzheng',
            name='zhuce_num',
            field=models.CharField(default='', max_length=30, verbose_name='注册号'),
        ),
    ]
