# Generated by Django 2.0.6 on 2019-06-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_auto_20190608_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renzheng',
            name='birth',
            field=models.CharField(default='', max_length=10, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='renzheng',
            name='end_date',
            field=models.CharField(default='', max_length=10, verbose_name='有效期结束时间'),
        ),
        migrations.AlterField(
            model_name='renzheng',
            name='start_date',
            field=models.CharField(default='', max_length=10, verbose_name='有效期起始时间'),
        ),
    ]
