# Generated by Django 2.0.6 on 2019-04-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_user'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('BS', '未上学'), ('KSSC', '幼儿园小小班'), ('KSC', '幼儿园小班'), ('KMC', '幼儿园中班'), ('KC', '幼儿园大班'), ('GO', '一年级'), ('GT', '二年级'), ('GTH', '三年级'), ('GF', '四年级'), ('GFI', '五年级'), ('GS', '六年级'), ('GSE', '初一'), ('GE', '初二'), ('GN', '初三'), ('HO', '高一'), ('HT', '高二'), ('HTW', '高三')], max_length=5, verbose_name='年级')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.CharField(choices=[('Child_care', '孩子看护'), ('After-school tutoring', '课后辅导'), ('Interest_development', '兴趣培养')], default='Child_care', max_length=50, verbose_name='服务类型')),
                ('charging_method', models.CharField(choices=[('Per_Hour', '每小时'), ('Per_Day', '每天'), ('Per_Month', '每月'), ('Per_Semester', '每学期'), ('Per_Quarter', '每季度')], default='Per_Month', max_length=20, verbose_name='收费方式')),
                ('time_num', models.PositiveIntegerField(verbose_name='托管时间')),
                ('price', models.PositiveIntegerField(verbose_name='收费金额')),
                ('admission_time', models.DateField(verbose_name='入学时间')),
                ('is_payment', models.BooleanField(default=False, verbose_name='是否已经付款')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='联系电话')),
                ('shangjia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Shangjia', verbose_name='所属商家')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.User', verbose_name='所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_location', models.CharField(max_length=256)),
                ('academic', models.CharField(choices=[('Dazhuan', '大专'), ('Benke', '本科'), ('Shuoshi', '硕士'), ('Boshi', '博士')], default='Dazhuan', max_length=20, verbose_name='学历要求')),
                ('subject', models.CharField(choices=[('Chinese', '语文'), ('Math', '数学'), ('English', '英语'), ('Biological', '生物'), ('Physical', '物理'), ('Chemistry', '化学'), ('History', '历史'), ('Geography', '地理'), ('Political', '政治')], default='Chinese', max_length=20)),
                ('price', models.PositiveIntegerField(verbose_name='月薪')),
                ('type', models.CharField(choices=[('Full_Time', '全职'), ('Part_Time', '兼职')], default='工作类型', max_length=20)),
                ('shangjia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shangjia', to='api.Shangjia')),
                ('user', models.ManyToManyField(related_name='user', to='authorization.User')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='order.Order'),
        ),
    ]
