# Generated by Django 2.0.6 on 2019-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190416_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='工作描述'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='position',
            field=models.CharField(max_length=50, null=True, verbose_name='职位'),
        ),
    ]
