# Generated by Django 2.0.6 on 2019-04-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190419_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to='authorization.Yonghu'),
        ),
    ]
