# Generated by Django 2.0.6 on 2019-04-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190419_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='shangjia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Shangjia'),
        ),
    ]
