# Generated by Django 2.2 on 2019-04-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190419_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='is_stop',
            field=models.BooleanField(null=True, verbose_name='是否结束'),
        ),
    ]
