# Generated by Django 2.0.6 on 2019-04-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_recruitment_is_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='is_stop',
            field=models.NullBooleanField(verbose_name='是否结束'),
        ),
    ]
