# Generated by Django 2.0.6 on 2019-04-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20190420_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_pingjia',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='未付款', max_length=128),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='academic',
            field=models.CharField(choices=[('Dazhuan', '大专'), ('Benke', '本科')], default='Dazhuan', max_length=20, verbose_name='学历要求'),
        ),
    ]
