# Generated by Django 2.0.6 on 2019-04-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_recruitment_peo_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='user',
            field=models.ManyToManyField(blank=True, to='authorization.Yonghu'),
        ),
    ]
