# Generated by Django 2.0.6 on 2019-06-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20190428_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='yonghu', to='authorization.Yonghu'),
        ),
    ]
