# Generated by Django 2.0.6 on 2019-06-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20190613_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='user_status',
            field=models.TextField(default='', verbose_name='用户状态'),
        ),
    ]
