# Generated by Django 2.0.6 on 2019-06-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_recruitment_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='R_Y_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.PositiveIntegerField(verbose_name='招聘信息id')),
                ('y_id', models.PositiveIntegerField(verbose_name='用户id')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
            ],
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='user_status',
        ),
    ]
